"use strict";
let car = "subaru";
console.log("car == 'subaru', This will be true");
console.log(car == "subaru");
console.log("car != 'subaru', This will be false");
console.log(car != "subaru");
console.log("car != 'Subaru', This will be true");
console.log(car != "Subaru");
console.log("car == 'SUBARU', This will be false");
console.log(car == "SUBARU");
console.log("car.length < 7, This will be true");
console.log(car.length < 7);
console.log("car.length > 6, This will be false");
console.log(car.length > 6);
console.log("car.length != 6, This will be false");
console.log(car.length != 6);
console.log("car.length <= 6, This will be true");
console.log(car.length <= 6);
console.log("car.length == 7 && car == 'subaru', This will be false");
console.log(car.length == 7 && car == "subaru");
console.log("car.length == 7 || car == 'subaru', This will be true");
console.log(car.length == 7 || car == "subaru");
